//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingPortal.AdService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ad", Namespace="http://schemas.datacontract.org/2004/07/TrainingPortal.Service.Advt.Entities")]
    [System.SerializableAttribute()]
    public partial class Ad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageExtensionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageExtension {
            get {
                return this.ImageExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageExtensionField, value) != true)) {
                    this.ImageExtensionField = value;
                    this.RaisePropertyChanged("ImageExtension");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdService.IAdRepos")]
    public interface IAdRepos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdRepos/GetAd", ReplyAction="http://tempuri.org/IAdRepos/GetAdResponse")]
        TrainingPortal.AdService.Ad[] GetAd();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdRepos/GetAd", ReplyAction="http://tempuri.org/IAdRepos/GetAdResponse")]
        System.Threading.Tasks.Task<TrainingPortal.AdService.Ad[]> GetAdAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdReposChannel : TrainingPortal.AdService.IAdRepos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdReposClient : System.ServiceModel.ClientBase<TrainingPortal.AdService.IAdRepos>, TrainingPortal.AdService.IAdRepos {
        
        public AdReposClient() {
        }
        
        public AdReposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdReposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdReposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdReposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrainingPortal.AdService.Ad[] GetAd() {
            return base.Channel.GetAd();
        }
        
        public System.Threading.Tasks.Task<TrainingPortal.AdService.Ad[]> GetAdAsync() {
            return base.Channel.GetAdAsync();
        }
    }
}
